name: Build and Publish DockerImage

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          tags: ${{ github.run_number }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - uses: actions/checkout@v2
        name: Check out code
        with:
          repository: case-study07/manifest
          
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image |= "docker.io/raityupiyo/cs-end-backend:'${IMAGE_TAG}'"' -i end-back-deployment.yaml
        env:
          IMAGE_TAG: ${{ github.run_number }} 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: |
              update container image
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: create-pull-request/release/${{ github.run_number }}
          base: main
